### ISSUE TITLE
.

### ISSUE THREAD

**Issue by vortex464** [ranenbg/Arduino-FFB-wheel#19]

**Comment by ranenbg** [comment]
Hi dude, first of all, it is pointless to post such a long compiler error list. I see that you didn't read my reply for your question about how to compile the source code. I'm copy pasting the instructions I wrpte in the readme file of the repository.

How to compile the source
In order to compile the firmware yourself you may use windows7, 8, 10 or 11, you need to install Arduino IDE v1.8.19 and Arduino Boards v1.6.21. You must place all [libraries](https://github.com/ranenbg/Arduino-FFB-wheel/tree/master/arduino-1.8.5/libraries) in your .../documents/Arduino/Libraries folder. In windows folder options set to show hidden files and folders then navigate to C:\Users\yourusername\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.21\cores. Rename the folder "arduino" as a backup as we will need some files from it latter, I just add "arduino_org" to the filename. Create a new folder called "arduino" and place the entire content from [modified core](https://github.com/ranenbg/Arduino-FFB-wheel/tree/master/arduino-1.8.5/hardware/arduino/cores/arduino) into newly created "arduino" folder. Navigate back to "arduino_org" folder and copy files "IPAddress.cpp", "IPAddress.h", "new.cpp" and "new.h", then paste and replace the ones inside the "arduino" folder. That should fix all errors and you should be able to compile the code. Bare in mind that if you make any changes to HID or USB core files you will need to repeat the procedure and paste all modified files in the newly created "arduino" folder each time.

**Comment by ranenbg** [comment]
Make sure to install Arduino boards 1.6.21 and copy and paste all the modified files to the correct location. Also make sure that in your Arduino IDE sketch, you have all the tabs with .h and .cpp files.
