### ISSUE TITLE
 Wiring of buttons.

### ISSUE THREAD

**Issue by lazenyuk-dmitry** [ranenbg/Arduino-FFB-wheel#2]
Somehow very difficult in your project with buttons. And you can make more buttons.
I think you could implement the same button connection as in this project like https://github.com/vsulako/AFFBWheel.

**Comment by ranenbg** [comment]
Hi Dmitry,

Tnx for your feedback.

My implementation of buttons is the same as in the project you mention. I'm
using a standard shift register protocol, except that instead of shift
register chips I'm using Arduino nano that simulates a shift register and
has 16 buttons. It is possible to just change one line of code and have the
ability to read more than 16 buttons when using shift register chips
stacked in series.

I believe that my wiring diagram shown on the button box wiring png is
clear enough, there is all information one needs, but you are right there
can be improvements I'll think about it and put a better picture. I did
show an example of wiring one button, but the same goes for all other
buttons, not sure what exactly is not clear there to you.

Best regards,
Milos.
