### ISSUE TITLE
z index 

### ISSUE THREAD

**Issue by vortex464** [ranenbg/Arduino-FFB-wheel#26]
How Encoder z-indexing works how it works

**Comment by ranenbg** [comment]
Hi, this is a very general question. The answer consits of 2 parts, one is understanding the hardware or how the encoder with 3 channels work and which signals it outputs on A, B and Z channel, this I will assume you already know.

Now the 2nd part is about firmware, or a routine which I implemented to support such encoders. The idea is that z-index pulse is always triggered at a fixed angle of encoder. Since the slit in z channel on encoder disc is very small, we can say that reaching towards this angle from both directions of rotation will trigger z-index pulse the same way. In practice, this is true for 1k ppr encoders, but for 2.5k ppr or above there may actually be 2 distinguishable angles, z+ and z-. To avoid this issue, I recommend to allways search z-index pulse from the same direction as when doing first z-index offset calibration. Depending how you mounted encoder on your wheel shaft this angle may end up anywhere inbetween 0-360deg, so you have to tell the firmware  how far is this angle from the actual zero angle of your wheel shaft. This you do by pressing z button in gui, then save. That way arduino will save this z-offset and store it in eeprom, such that on next power up as soon as z-index pulse is detected, this offset will be applied to the curent angle and voila, that's it :)
